/**
 * Helper class for generating standardized REST API replies
 * @param {Object} ctx - The object representing the context for a request/response instance
 * @param {String} query - A string defining the purpose of the request
 * @param {Object} payload - The resultant reply generated by the request.
 *
 * @returns {Object}
 */
class Response {
  constructor(ctx, query, payload) {
    if (ctx.status < 400) {
      this.data = payload;
    } else {
      this.error = payload;
    }
    this.status = ctx.status;
    this.query = query;
  }
}

module.exports = Response;
